name: Comment

on: 
  pull_request:
    branches: ["*"]

jobs:
  comment: # the job's name
    runs-on: ubuntu-latest
    steps:
      - env: 
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$(curl 'https://api.open-meteo.com/v1/forecast?latitude=24.4764&longitude=54.3705&current_weather=true')
          export weather=$(echo $body | jq '.current_weather.temperature')
          gh pr comment $PR_NUMBER --body "the temperature is: $weather" --repo $GITHUB_REPOSITORY

